package hu.bme.onlab.post.bean;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.PropertyDefinition;
import java.util.Map;
import java.util.Set;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
public class CheckAddressRequest implements Bean {

	@PropertyDefinition
	private String postalCode;
	
	//------------------------- AUTOGENERATED START -------------------------
	///CLOVER:OFF
	/**
	 * The meta-bean for {@code CheckAddressRequest}.
	 * @return the meta-bean, not null
	 */
	public static CheckAddressRequest.Meta meta() {
		return CheckAddressRequest.Meta.INSTANCE;
	}

	static {
		JodaBeanUtils.registerMetaBean(CheckAddressRequest.Meta.INSTANCE);
	}

	@Override
	public CheckAddressRequest.Meta metaBean() {
		return CheckAddressRequest.Meta.INSTANCE;
	}

	@Override
	public <R> Property<R> property(String propertyName) {
		return metaBean().<R>metaProperty(propertyName).createProperty(this);
	}

	@Override
	public Set<String> propertyNames() {
		return metaBean().metaPropertyMap().keySet();
	}

	//-----------------------------------------------------------------------
	/**
	 * Gets the postalCode.
	 * @return the value of the property
	 */
	public String getPostalCode() {
		return postalCode;
	}

	/**
	 * Sets the postalCode.
	 * @param postalCode  the new value of the property
	 */
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	/**
	 * Gets the the {@code postalCode} property.
	 * @return the property, not null
	 */
	public final Property<String> postalCode() {
		return metaBean().postalCode().createProperty(this);
	}

	//-----------------------------------------------------------------------
	@Override
	public CheckAddressRequest clone() {
		return JodaBeanUtils.cloneAlways(this);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == this) {
			return true;
		}
		if (obj != null && obj.getClass() == this.getClass()) {
			CheckAddressRequest other = (CheckAddressRequest) obj;
			return JodaBeanUtils.equal(getPostalCode(), other.getPostalCode());
		}
		return false;
	}

	@Override
	public int hashCode() {
		int hash = getClass().hashCode();
		hash = hash * 31 + JodaBeanUtils.hashCode(getPostalCode());
		return hash;
	}

	@Override
	public String toString() {
		StringBuilder buf = new StringBuilder(64);
		buf.append("CheckAddressRequest{");
		int len = buf.length();
		toString(buf);
		if (buf.length() > len) {
			buf.setLength(buf.length() - 2);
		}
		buf.append('}');
		return buf.toString();
	}

	protected void toString(StringBuilder buf) {
		buf.append("postalCode").append('=').append(JodaBeanUtils.toString(getPostalCode())).append(',').append(' ');
	}

	//-----------------------------------------------------------------------
	/**
	 * The meta-bean for {@code CheckAddressRequest}.
	 */
	public static class Meta extends DirectMetaBean {
		/**
		 * The singleton instance of the meta-bean.
		 */
		static final Meta INSTANCE = new Meta();

		/**
		 * The meta-property for the {@code postalCode} property.
		 */
		private final MetaProperty<String> postalCode = DirectMetaProperty.ofReadWrite(
				this, "postalCode", CheckAddressRequest.class, String.class);
		/**
		 * The meta-properties.
		 */
		private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
				this, null,
				"postalCode");

		/**
		 * Restricted constructor.
		 */
		protected Meta() {
		}

		@Override
		protected MetaProperty<?> metaPropertyGet(String propertyName) {
			switch (propertyName.hashCode()) {
				case 2011152728:  // postalCode
					return postalCode;
			}
			return super.metaPropertyGet(propertyName);
		}

		@Override
		public BeanBuilder<? extends CheckAddressRequest> builder() {
			return new DirectBeanBuilder<CheckAddressRequest>(new CheckAddressRequest());
		}

		@Override
		public Class<? extends CheckAddressRequest> beanType() {
			return CheckAddressRequest.class;
		}

		@Override
		public Map<String, MetaProperty<?>> metaPropertyMap() {
			return metaPropertyMap$;
		}

		//-----------------------------------------------------------------------
		/**
		 * The meta-property for the {@code postalCode} property.
		 * @return the meta-property, not null
		 */
		public final MetaProperty<String> postalCode() {
			return postalCode;
		}

		//-----------------------------------------------------------------------
		@Override
		protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
			switch (propertyName.hashCode()) {
				case 2011152728:  // postalCode
					return ((CheckAddressRequest) bean).getPostalCode();
			}
			return super.propertyGet(bean, propertyName, quiet);
		}

		@Override
		protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
			switch (propertyName.hashCode()) {
				case 2011152728:  // postalCode
					((CheckAddressRequest) bean).setPostalCode((String) newValue);
					return;
			}
			super.propertySet(bean, propertyName, newValue, quiet);
		}

	}

	///CLOVER:ON
	//-------------------------- AUTOGENERATED END --------------------------
}
