package hu.bme.onlab.user.bean;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import java.util.Map;
import java.util.Set;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.joda.beans.impl.direct.DirectMetaProperty;


@BeanDefinition
public class PasswordChangeRequest implements Bean {

    @PropertyDefinition(validate = "notEmpty")
    private String newPassword;
    
    //------------------------- AUTOGENERATED START -------------------------
    ///CLOVER:OFF
    /**
     * The meta-bean for {@code PasswordChangeRequest}.
     * @return the meta-bean, not null
     */
    public static PasswordChangeRequest.Meta meta() {
        return PasswordChangeRequest.Meta.INSTANCE;
    }

    static {
        JodaBeanUtils.registerMetaBean(PasswordChangeRequest.Meta.INSTANCE);
    }

    @Override
    public PasswordChangeRequest.Meta metaBean() {
        return PasswordChangeRequest.Meta.INSTANCE;
    }

    @Override
    public <R> Property<R> property(String propertyName) {
        return metaBean().<R>metaProperty(propertyName).createProperty(this);
    }

    @Override
    public Set<String> propertyNames() {
        return metaBean().metaPropertyMap().keySet();
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the newPassword.
     * @return the value of the property, not empty
     */
    public String getNewPassword() {
        return newPassword;
    }

    /**
     * Sets the newPassword.
     * @param newPassword  the new value of the property, not empty
     */
    public void setNewPassword(String newPassword) {
        JodaBeanUtils.notEmpty(newPassword, "newPassword");
        this.newPassword = newPassword;
    }

    /**
     * Gets the the {@code newPassword} property.
     * @return the property, not null
     */
    public final Property<String> newPassword() {
        return metaBean().newPassword().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public PasswordChangeRequest clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            PasswordChangeRequest other = (PasswordChangeRequest) obj;
            return JodaBeanUtils.equal(getNewPassword(), other.getNewPassword());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getNewPassword());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("PasswordChangeRequest{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("newPassword").append('=').append(JodaBeanUtils.toString(getNewPassword())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code PasswordChangeRequest}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code newPassword} property.
         */
        private final MetaProperty<String> newPassword = DirectMetaProperty.ofReadWrite(
                this, "newPassword", PasswordChangeRequest.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "newPassword");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1821235109:  // newPassword
                    return newPassword;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends PasswordChangeRequest> builder() {
            return new DirectBeanBuilder<PasswordChangeRequest>(new PasswordChangeRequest());
        }

        @Override
        public Class<? extends PasswordChangeRequest> beanType() {
            return PasswordChangeRequest.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code newPassword} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> newPassword() {
            return newPassword;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1821235109:  // newPassword
                    return ((PasswordChangeRequest) bean).getNewPassword();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1821235109:  // newPassword
                    ((PasswordChangeRequest) bean).setNewPassword((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

        @Override
        protected void validate(Bean bean) {
            JodaBeanUtils.notEmpty(((PasswordChangeRequest) bean).newPassword, "newPassword");
        }

    }

    ///CLOVER:ON
    //-------------------------- AUTOGENERATED END --------------------------
}
