package hu.bme.onlab.user.bean;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.PropertyDefinition;

import java.util.List;
import java.util.Map;
import java.util.Set;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import hu.bme.onlab.user.domain.Role;

@BeanDefinition
public class UserManagementPreloadReply implements Bean  {
    
    @PropertyDefinition
    private List<RoleDTO> roles;

    //------------------------- AUTOGENERATED START -------------------------
    ///CLOVER:OFF
    /**
     * The meta-bean for {@code UserManagementPreloadReply}.
     * @return the meta-bean, not null
     */
    public static UserManagementPreloadReply.Meta meta() {
        return UserManagementPreloadReply.Meta.INSTANCE;
    }

    static {
        JodaBeanUtils.registerMetaBean(UserManagementPreloadReply.Meta.INSTANCE);
    }

    @Override
    public UserManagementPreloadReply.Meta metaBean() {
        return UserManagementPreloadReply.Meta.INSTANCE;
    }

    @Override
    public <R> Property<R> property(String propertyName) {
        return metaBean().<R>metaProperty(propertyName).createProperty(this);
    }

    @Override
    public Set<String> propertyNames() {
        return metaBean().metaPropertyMap().keySet();
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the roles.
     * @return the value of the property
     */
    public List<RoleDTO> getRoles() {
        return roles;
    }

    /**
     * Sets the roles.
     * @param roles  the new value of the property
     */
    public void setRoles(List<RoleDTO> roles) {
        this.roles = roles;
    }

    /**
     * Gets the the {@code roles} property.
     * @return the property, not null
     */
    public final Property<List<RoleDTO>> roles() {
        return metaBean().roles().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public UserManagementPreloadReply clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            UserManagementPreloadReply other = (UserManagementPreloadReply) obj;
            return JodaBeanUtils.equal(getRoles(), other.getRoles());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getRoles());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("UserManagementPreloadReply{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("roles").append('=').append(JodaBeanUtils.toString(getRoles())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code UserManagementPreloadReply}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code roles} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<RoleDTO>> roles = DirectMetaProperty.ofReadWrite(
                this, "roles", UserManagementPreloadReply.class, (Class) List.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "roles");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 108695229:  // roles
                    return roles;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends UserManagementPreloadReply> builder() {
            return new DirectBeanBuilder<UserManagementPreloadReply>(new UserManagementPreloadReply());
        }

        @Override
        public Class<? extends UserManagementPreloadReply> beanType() {
            return UserManagementPreloadReply.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code roles} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<RoleDTO>> roles() {
            return roles;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 108695229:  // roles
                    return ((UserManagementPreloadReply) bean).getRoles();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 108695229:  // roles
                    ((UserManagementPreloadReply) bean).setRoles((List<RoleDTO>) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    ///CLOVER:ON
    //-------------------------- AUTOGENERATED END --------------------------
}
