package hu.bme.archi.issue.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
public class ListProjectsResponse implements Bean {
    
    @PropertyDefinition
    List<ListProjectsData> projects = new ArrayList<>();
    //------------------------- AUTOGENERATED START -------------------------
    ///CLOVER:OFF
    /**
     * The meta-bean for {@code ListProjectsResponse}.
     * @return the meta-bean, not null
     */
    public static ListProjectsResponse.Meta meta() {
        return ListProjectsResponse.Meta.INSTANCE;
    }

    static {
        JodaBeanUtils.registerMetaBean(ListProjectsResponse.Meta.INSTANCE);
    }

    @Override
    public ListProjectsResponse.Meta metaBean() {
        return ListProjectsResponse.Meta.INSTANCE;
    }

    @Override
    public <R> Property<R> property(String propertyName) {
        return metaBean().<R>metaProperty(propertyName).createProperty(this);
    }

    @Override
    public Set<String> propertyNames() {
        return metaBean().metaPropertyMap().keySet();
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the projects.
     * @return the value of the property
     */
    public List<ListProjectsData> getProjects() {
        return projects;
    }

    /**
     * Sets the projects.
     * @param projects  the new value of the property
     */
    public void setProjects(List<ListProjectsData> projects) {
        this.projects = projects;
    }

    /**
     * Gets the the {@code projects} property.
     * @return the property, not null
     */
    public final Property<List<ListProjectsData>> projects() {
        return metaBean().projects().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public ListProjectsResponse clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            ListProjectsResponse other = (ListProjectsResponse) obj;
            return JodaBeanUtils.equal(getProjects(), other.getProjects());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getProjects());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("ListProjectsResponse{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("projects").append('=').append(JodaBeanUtils.toString(getProjects())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code ListProjectsResponse}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code projects} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<ListProjectsData>> projects = DirectMetaProperty.ofReadWrite(
                this, "projects", ListProjectsResponse.class, (Class) List.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "projects");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -998696838:  // projects
                    return projects;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends ListProjectsResponse> builder() {
            return new DirectBeanBuilder<ListProjectsResponse>(new ListProjectsResponse());
        }

        @Override
        public Class<? extends ListProjectsResponse> beanType() {
            return ListProjectsResponse.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code projects} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<ListProjectsData>> projects() {
            return projects;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -998696838:  // projects
                    return ((ListProjectsResponse) bean).getProjects();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -998696838:  // projects
                    ((ListProjectsResponse) bean).setProjects((List<ListProjectsData>) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    ///CLOVER:ON
    //-------------------------- AUTOGENERATED END --------------------------
}
