package hu.bme.archi.user.bean;

import org.joda.beans.PropertyDefinition;

import java.util.List;
import java.util.Map;
import java.util.Set;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
public class ModifyUserRequest implements Bean {

    @PropertyDefinition
    private String email;
    @PropertyDefinition
    private List<Long> projectIds;
    @PropertyDefinition
    private Long roleId;
    //------------------------- AUTOGENERATED START -------------------------
    ///CLOVER:OFF
    /**
     * The meta-bean for {@code ModifyUserRequest}.
     * @return the meta-bean, not null
     */
    public static ModifyUserRequest.Meta meta() {
        return ModifyUserRequest.Meta.INSTANCE;
    }

    static {
        JodaBeanUtils.registerMetaBean(ModifyUserRequest.Meta.INSTANCE);
    }

    @Override
    public ModifyUserRequest.Meta metaBean() {
        return ModifyUserRequest.Meta.INSTANCE;
    }

    @Override
    public <R> Property<R> property(String propertyName) {
        return metaBean().<R>metaProperty(propertyName).createProperty(this);
    }

    @Override
    public Set<String> propertyNames() {
        return metaBean().metaPropertyMap().keySet();
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the email.
     * @return the value of the property
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email.
     * @param email  the new value of the property
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the the {@code email} property.
     * @return the property, not null
     */
    public final Property<String> email() {
        return metaBean().email().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the projectIds.
     * @return the value of the property
     */
    public List<Long> getProjectIds() {
        return projectIds;
    }

    /**
     * Sets the projectIds.
     * @param projectIds  the new value of the property
     */
    public void setProjectIds(List<Long> projectIds) {
        this.projectIds = projectIds;
    }

    /**
     * Gets the the {@code projectIds} property.
     * @return the property, not null
     */
    public final Property<List<Long>> projectIds() {
        return metaBean().projectIds().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the roleId.
     * @return the value of the property
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * Sets the roleId.
     * @param roleId  the new value of the property
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * Gets the the {@code roleId} property.
     * @return the property, not null
     */
    public final Property<Long> roleId() {
        return metaBean().roleId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public ModifyUserRequest clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            ModifyUserRequest other = (ModifyUserRequest) obj;
            return JodaBeanUtils.equal(getEmail(), other.getEmail()) &&
                    JodaBeanUtils.equal(getProjectIds(), other.getProjectIds()) &&
                    JodaBeanUtils.equal(getRoleId(), other.getRoleId());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getEmail());
        hash = hash * 31 + JodaBeanUtils.hashCode(getProjectIds());
        hash = hash * 31 + JodaBeanUtils.hashCode(getRoleId());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(128);
        buf.append("ModifyUserRequest{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("email").append('=').append(JodaBeanUtils.toString(getEmail())).append(',').append(' ');
        buf.append("projectIds").append('=').append(JodaBeanUtils.toString(getProjectIds())).append(',').append(' ');
        buf.append("roleId").append('=').append(JodaBeanUtils.toString(getRoleId())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code ModifyUserRequest}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code email} property.
         */
        private final MetaProperty<String> email = DirectMetaProperty.ofReadWrite(
                this, "email", ModifyUserRequest.class, String.class);
        /**
         * The meta-property for the {@code projectIds} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<Long>> projectIds = DirectMetaProperty.ofReadWrite(
                this, "projectIds", ModifyUserRequest.class, (Class) List.class);
        /**
         * The meta-property for the {@code roleId} property.
         */
        private final MetaProperty<Long> roleId = DirectMetaProperty.ofReadWrite(
                this, "roleId", ModifyUserRequest.class, Long.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "email",
                "projectIds",
                "roleId");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 96619420:  // email
                    return email;
                case -1969991457:  // projectIds
                    return projectIds;
                case -925416399:  // roleId
                    return roleId;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends ModifyUserRequest> builder() {
            return new DirectBeanBuilder<ModifyUserRequest>(new ModifyUserRequest());
        }

        @Override
        public Class<? extends ModifyUserRequest> beanType() {
            return ModifyUserRequest.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code email} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> email() {
            return email;
        }

        /**
         * The meta-property for the {@code projectIds} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<Long>> projectIds() {
            return projectIds;
        }

        /**
         * The meta-property for the {@code roleId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Long> roleId() {
            return roleId;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 96619420:  // email
                    return ((ModifyUserRequest) bean).getEmail();
                case -1969991457:  // projectIds
                    return ((ModifyUserRequest) bean).getProjectIds();
                case -925416399:  // roleId
                    return ((ModifyUserRequest) bean).getRoleId();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 96619420:  // email
                    ((ModifyUserRequest) bean).setEmail((String) newValue);
                    return;
                case -1969991457:  // projectIds
                    ((ModifyUserRequest) bean).setProjectIds((List<Long>) newValue);
                    return;
                case -925416399:  // roleId
                    ((ModifyUserRequest) bean).setRoleId((Long) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    ///CLOVER:ON
    //-------------------------- AUTOGENERATED END --------------------------
}
